# Tareas que se deben hacer en todos los ordenadores

# Desactivar la actualización automática de seguridad (núcleo)
#- include: /home/vcarceler/playbooks/deactivate-unattended-upgrades.yml

# Configura la actualización automática con unattended-upgrades
- include: activate-unattended-upgrades.yml

# Instala Vasilisa para mantener libre espacio en disco
- include: vasilisa.yml

# Instala y configura Telegraf
- include: telegraf.yml

# Apagado a las 21:30
- include: apagado-2130.yml
