---
- hosts: portatiles-prestamo
  user: root
  connection: paramiko
  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,plugdev,sambashare,ubridge,vboxusers

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

  tasks:
    # Tareas por defecto
    - include: default.yml

    # Cambio de hostname
    - include: /home/vcarceler/playbooks/cambia-hostname.yml base_hostname=portatil

    # Cambio en la configuración de sshd para bloquear la autenticación con password
    - name: Bloquea la autenticación con password en /etc/ssh/sshd_config
      replace:
        dest: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'
      notify:
        - restart sshd

    # Tareas particulares de las aulas de informática
    - include: apagado-1455.yml
    
    # Tareas generales de informática (DPT y Aulas)
    #

    # Borrado de usuarios por defecto (mati y tarda)
    - include: del-default-users.yml

    # Usuario invitado
    - include: convidat.yml

    # Gnome3 dconf
    - include: gnome3-dconf.yml

    # Instalación general de paquetes para Informàtica (DPT y Aulas)
    - include: informatica-paquetes-u1804.yml

    # Usuarios
    - include: users/dam2a.yml
    - include: users/dam2b.yml
    - include: users/afcat.yml
    - include: users/afeng.yml
    - include: users/docent.yml

    # Actualiza el SO
    - include: upgrade.yml
